[package]
name = "kalnal-kmer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bio = "*"
custom_error = "1.9.2"
dashmap = "5.4.0"
fxhash = "0.2.1"
rayon = "*"
insta = "*"
